version: '3'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "0.0.0.0:5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata  # Replace with your timezone
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=ishika2236
      - N8N_BASIC_AUTH_PASSWORD=Success@223624
    volumes:
      - ./n8n_data:/home/node/.n8n

